
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        output:
          destination: original1
          binder: kafka
          auto-offset-reset: latest


