spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test_database
    username: postgres
    password: 1234
    initialization-mode: always
    continue-on-error: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: modified_values
          binder: kafka
          group: example-group45




