spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: original1
          binder: kafka
          group: example-group-processor
          auto-offset-reset: latest
        output:
          destination: modified_values
          binder: kafka
          group: example-group-processor
